spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    
liquibase:
  change-log: classpath:services/credit/liquibase/changelogs/db.changelog-master.sql
  contexts: development
  default-schema: public
  drop-first: false
  enabled: true